### ISSUE TITLE
`HttpEventCollectorLoggingHandler` does not honor the current level

### ISSUE THREAD

**Issue by asmyers** [splunk/splunk-library-javalogging#203] opened 2021-09-29 20:13 UTC
Calling `setLevel` on an instance of `HttpEventCollectorLoggingHandler` has no effect because the [publish method](https://github.com/splunk/splunk-library-javalogging/blob/bfd169b18c180b7deee4a7c3d434991f6a0c7d4c/src/main/java/com/splunk/logging/HttpEventCollectorLoggingHandler.java#L226) does not check the current log level.

JDK implementations of `Handler`, such as [`StreamHandler`](https://github.com/openjdk/jdk/blob/739769c8fc4b496f08a92225a12d07414537b6c0/src/java.logging/share/classes/java/util/logging/StreamHandler.java#L193) check the [`isLoggable`](https://github.com/openjdk/jdk/blob/739769c8fc4b496f08a92225a12d07414537b6c0/src/java.logging/share/classes/java/util/logging/Handler.java#L336) method prior to publishing.

The impact of this is that I cannot disable the `HttpEventCollectorLoggingHandler` by calling `setLevel(OFF)`.   As a result I cannot implement a HEC error handler that logs an error to other configured log handlers like this:

```java
        HttpEventCollectorErrorHandler.onError((infoList, exception) -> {
            final Optional<HttpEventCollectorLoggingHandler> collector = getEventCollectorHandler();
            collector.ifPresent(hec -> {
                hec.setLevel(Level.OFF);
            });
            logger.severe(exception.getMessage());
       }
```

**Comment by bparmar-splunk** [comment] 2022-08-17 07:15
Hi @asmyers,
Thanks for reaching out !

To set the Logger Level to OFF, you have to make below change in **jdklogging.properties** file.
`# Implicitly create a logger with name 'splunk.logger' (user-defined), set its level to INFO | WARNING | SEVERE | OFF.`
`splunk.logger.level = OFF`

Please apply this change and try to re-validate your use-case and let us know in case of any issues.

**Comment by bparmar-splunk** [comment] 2022-09-01 07:56
Hi @asmyers,
Since we do not get any update from you about this issue.
We assume that the issue is resolved based on the above [comment](https://github.com/splunk/splunk-library-javalogging/issues/203#issuecomment-1217552821).

Closing this issue for now.
Please let us know in case of any further queries.

Thank you.

**Closed by bparmar-splunk** 2022-09-01 07:56 UTC
