### ISSUE TITLE
cannot send to event endpoint with idx ack enabled on token with HttpEventCollectorLogbackAppender

### ISSUE THREAD

**Issue by ManickamA** [splunk/splunk-library-javalogging#159] opened 2020-09-04 20:02 UTC
idx ack enabled on token, channel is needed and currently channel is used only on raw endpoint and not for event endpoint. we are using HttpEventCollectorLogbackAppender and getting the Data channel is missing even with channel defined on appender ..

<appender name="SPLUNK" class="com.splunk.logging.HttpEventCollectorLogbackAppender">
    <url>*********</url>
    <index>np-***</index>
    <token>*********</token>
    <type>event</type>
    <sourceType>log4j</sourceType>
    <channel>*********</channel>
    <disableCertificateValidation>true</disableCertificateValidation>
    <layout class="ch.qos.logback.classic.PatternLayout">
        <pattern>${pattern}</pattern>
    </layout>
</appender>

**Comment by pearj** [comment] 2020-12-02 01:27
For me on Java Util logging I discovered that you have to set the type to raw and then set a channel 

https://github.com/splunk/splunk-library-javalogging/blob/9d5b49323573d6476a0c781a9e6228c70bf90fd5/src/main/java/com/splunk/logging/HttpEventCollectorLoggingHandler.java#L139-L143

As it can only use the channel in raw mode as seen here:
https://github.com/splunk/splunk-library-javalogging/blob/9d5b49323573d6476a0c781a9e6228c70bf90fd5/src/main/java/com/splunk/logging/HttpEventCollectorSender.java#L337-L339

```
com.splunk.logging.HttpEventCollectorLoggingHandler.url = http://splunkhec
com.splunk.logging.HttpEventCollectorLoggingHandler.level = ALL
com.splunk.logging.HttpEventCollectorLoggingHandler.channel = <generate a guid and put it here>
com.splunk.logging.HttpEventCollectorLoggingHandler.type = raw
com.splunk.logging.HttpEventCollectorLoggingHandler.token = <hec token>
com.splunk.logging.HttpEventCollectorLoggingHandler.disableCertificateValidation=true
```

If your logback xml file, I think you just need to add `<channel>generate a guid and put it here</channel>` and `<type>raw</type>`

The channel guid can be anything as discussed here: https://community.splunk.com/t5/Getting-Data-In/How-to-setup-a-channel-to-send-raw-data-to-HTTP-event-collector/m-p/298460

**Comment by bparmar-splunk** [comment] 2022-09-08 05:00
Hi @ManickamA,
We have tried to reproduce the issue which you faced while using index acknowledgement with token. Below are the findings:

- Suggestions provided by @pearj are correct. In configuration, it works only in **RAW** type and setting a **channel** value is mandatory.
- When RAW mode is used, **avoid** setting batch count attribute. Setting both values (raw-type and batch-count) are incompatible.

Please let us know if you face any issue.

Also, we would recommend to update the library to recently launched version [1.11.6](https://github.com/splunk/splunk-library-javalogging/releases/tag/1.11.6). It has covered many resolved issues and few enhancements since the version you were using.

**Comment by bparmar-splunk** [comment] 2022-09-26 04:17
Hi @ManickamA,
We have not heard anything from you.
The issue which you have faced might get resolved based on above [comment](https://github.com/splunk/splunk-library-javalogging/issues/159#issuecomment-1240222306).

We are closing this issue for now.
Please let us know if you still face any issue.

Thank you.

**Closed by bparmar-splunk** 2022-09-26 04:17 UTC
