### ISSUE TITLE
Broken splunk-library-javalogging:1.8.0 on the maven repository

### ISSUE THREAD

**Issue by kkulak** [splunk/splunk-library-javalogging#144] opened 2020-03-23 10:30 UTC
Hi,

1.8.0 version of the lib seems to be broken on the mvn central repository. Can you upload the fixed one, please?

We're seeing the following error in our builds:
```
   > Could not resolve com.splunk.logging:splunk-library-javalogging:1.8.0.
     Required by:
         project :my-project
      > Could not resolve com.splunk.logging:splunk-library-javalogging:1.8.0.
         > Could not parse POM http://splunk.artifactoryonline.com/splunk/ext-releases-local/com/splunk/logging/splunk-library-javalogging/1.8.0/splunk-library-javalogging-1.8.0.pom
            > The element type "hr" must be terminated by the matching end-tag "</hr>".
```

thanks,
Kamil

**Comment by akauppi** [comment] 2020-03-23 13:22
Did not know it's expected to be available at Maven Central.

The installation instructions instruct to add this:

```
    <repositories>
        <repository>
            <id>splunk-artifactory</id>
            <name>Splunk Releases</name>
            <url>https://splunk.jfrog.io/splunk/ext-releases-local</url>
        </repository>
    </repositories>
```

**Comment by fantavlik** [comment] 2020-03-23 22:05
@akauppi is correct we host our Maven artifacts on splunk.jfrog.io, see the Java Logging Library installation instructions: https://dev.splunk.com/enterprise/docs/java/logging-java/getstartedloggingjava/installloggingjava#Use-Maven if you run into any issues please re-open this though the artifacts appear to be there as expected for 1.8.0: https://splunk.jfrog.io/artifactory/ext-releases-local/com/splunk/logging/splunk-library-javalogging/1.8.0/

**Comment by fantavlik** [comment] 2020-03-23 22:19
Actually I think I was premature in closing this, the POM issue does appear to point to our hosted file on http://splunk.artifactoryonline.com/splunk/ext-releases-local/com/splunk/logging/splunk-library-javalogging/1.8.0/splunk-library-javalogging-1.8.0.pom though I'm confused by the error reported since there are clearly no `<hr>` elements in the POM file itself. Let me attempt to reproduce.

**Comment by fantavlik** [comment] 2020-03-23 23:12
Closing as I'm not able to repro, I have a test project with a POM file as follows with Java Logging Library version 1.8.0 as a dependency and the project builds as expected:
```html
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  ...
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
    <repositories>
        <repository>
            <id>splunk-artifactory</id>
            <name>Splunk Releases</name>
            <url>http://splunk.jfrog.io/splunk/ext-releases-local</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>com.splunk.logging</groupId>
            <artifactId>splunk-library-javalogging</artifactId>
            <version>1.8.0</version>
        </dependency>
        ...
    </dependencies>
</project>
```
@kkulak can you try updating your config to match the above and retry?

**Closed by fantavlik** 2020-03-23 23:12 UTC
