### ISSUE TITLE
Configuring HttpEventCollectorLog4jAppender

### ISSUE THREAD

**Issue by rasmusviben** [splunk/splunk-library-javalogging#97] opened 2019-01-09 13:29 UTC
Hi,

I'm trying to configure the Http appender with log4j2 through .xml with Spring boot 2.

My Appender looks like this:

        <Http name="http"
              url="${splunk.url}"
              token="${splunk.token}"
              disableCertificateValidation="true"
              index="freshcatch"
              host="${splunk.hostname}"
              source="Test123"
              sourcetype="test-log">
            <PatternLayout pattern="%msg"/>
        </Http>

Spring boot reads the configuration, but when it starts up the the following error is shown:

`main ERROR Http contains invalid attributes "disableCertificateValidation", "host", "index", "sourcetype", "source", "token"`

In your plugin class HttpEventCollectorLog4jAppender, the attributes is included, but why are they not configurable in the log4j2.xml?

Maybe I'm missing something here - hope to get some help. :)

**Comment by polpak** [comment] 2019-01-11 23:49
This is a duplicate of https://github.com/splunk/splunk-library-javalogging/issues/80 which is fixed in version 1.7.0.

**Closed** 2019-02-05 22:02 UTC
