### ISSUE TITLE
ClastCastException in 1.11.6 by LogLevel Level.ERROR

### ISSUE THREAD

**Issue by JanGoerss** [splunk/splunk-library-javalogging#259] opened 2022-09-19 10:44 UTC
Hi,

logging in 1.11.6 throw a ClassCastException and every error log is not sent over HttpEventCollector to SplunkServer

java.lang.ClassCastException: class org.apache.logging.log4j.core.impl.Log4jLogEvent cannot be cast to class org.apache.logging.log4j.core.impl.MutableLogEvent (org.apache.logging.log4j.core.impl.Log4jLogEvent and org.apache.logging.log4j.core.impl.MutableLogEvent are in unnamed module of loader 'app')
	at com.splunk.logging.HttpEventCollectorLog4jAppender.generateErrorDetail(HttpEventCollectorLog4jAppender.java:275)

Environment:
Java 17
Splunklogging 1.11.6
log4j 2.17.2
slf4j 1.7.36

**Comment by bparmar-splunk** [comment] 2022-09-22 03:57
Hi @JanGoerss,
Thank you for reaching out.

We have tried to reproduce the issue which you faced in our local, but it worked well. We have used all above versions which you mentioned, in our local test.
It seems there are multiple versions of Log4J library on your machine.
Please try to remove all dependencies from local maven repo and re-check again the same use case.

If it does not work, then please do share us the detail steps to reproduce.

**Comment by bparmar-splunk** [comment] 2022-09-22 08:19
Hi @JanGoerss,
We have tried using your application and below are our findings:

- The configurations in log4j2.xml file was not proper as per Splunk doc. Please refer [Splunk doc](https://dev.splunk.com/enterprise/docs/devtools/java/logging-java/howtouseloggingjava/enableloghttpjava).
- We have tried changing the configuration as per doc and it started working.
Also, we are attaching a file with revised configuration settings. Please verify your changes and let us know about your test results.
File: 
[log4j2.xml.zip](https://github.com/splunk/splunk-library-javalogging/files/9623794/log4j2.xml.zip)

**Comment by bparmar-splunk** [comment] 2022-09-22 11:53
HI @JanGoerss,
Thank you for your response.

We have used MutableLogEvent because we want exception details from parameters when it does not have any information in getThrown() method. And by using its parent, we cannot fetch its parameters.

Also, We are open for any suggestion OR PR which can support for your use-case.

**Comment by MartinHeinen** [comment] 2022-09-26 12:08
We are running into the same issue after upgrading to version 1.11.6
This issue causes our threads reading from a RabbitMQ Queue to be cancelled and slowly stopping all our processing, so we had to downgrade back to 1.11.5.
Is there a way to address this?
In general, I was surprised, that a logging library would throw an exception in the first place. Is it the expectation to always try/catch logging or are there other ways we can avoid running into an exception?
Additionally, I would suggest, to firstly check if the cast to MutableLogEvent is possible and if not log the event as done before the version upgrade.

Kind regards,

Martin

**Comment by bparmar-splunk** [comment] 2022-09-27 03:51
Hi @MartinHeinen,
Thank you for raising this up.

We will look into this issue and will update you and @JanGoerss for the fix.
Thank you.

**Comment by bparmar-splunk** [comment] 2022-09-30 04:22
Hi @MartinHeinen & @JanGoerss,
We have fixed the issue in our local. We are yet to push and release with new minor version. But before that we would request you guys to test the build in your application using a jar file (attached here) just to make sure that the issue has been resolved in both the use-cases.
JAR: 
[splunk-library-javalogging-1.11.6.jar.zip](https://github.com/splunk/splunk-library-javalogging/files/9680713/splunk-library-javalogging-1.11.6.jar.zip)

Please share your results once you test your application.

Thank you.

**Comment by bparmar-splunk** [comment] 2022-10-04 06:02
Hi @JanGoerss,
Thank you for the update.

We are still waiting for the response from @MartinHeinen, if it works well then we will plan a minor release post that.

Thank you.

**Comment by MartinHeinen** [comment] 2022-10-10 14:13
Hi,

For us it's not easy to reproduce the issue in Pre-Production, but during our testing we did not run into any issues with the jar you provided and the exception did not occur again so far.

Thanks

**Comment by bparmar-splunk** [comment] 2022-10-11 04:03
Hi @MartinHeinen,
Thank you for the update.
We will plan for a release soon and will post new version link here.

Thanks.

**Comment by bparmar-splunk** [comment] 2022-10-12 04:51
Hi @JanGoerss & @MartinHeinen,
We have successfully released new version [1.11.7](https://github.com/splunk/splunk-library-javalogging/releases/tag/1.11.7) of this library.

Please update your library to this version.
We are closing this issue.

Thank you.

**Closed by bparmar-splunk** 2022-10-12 04:51 UTC
