### ISSUE TITLE
Not work with tomcat 8

### ISSUE THREAD

**Issue by plttlqh** [splunk/splunk-library-javalogging#46] opened 2017-01-13 08:00 UTC
Hi guys,

I had a problem when upgrade to tomcat 8. HttpEventCollectorLogbackAppender was not contruct but on tomcat 7 It does.

Thanks,
Ha Le

**Comment by shakeelmohamed** [comment] 2017-01-13 21:53
Hi @plttlqh,

We'll need a bit more information in order to help

**Comment by plttlqh** [comment] 2017-01-14 01:21
My application is spring mvc, imported logback, slf4j which run on tomcat7, jdk 8 then the application send a message to splunk server. Other way, I only changed tomcat 8 then It not worked. I have no idea.

**Comment by shakeelmohamed** [comment] 2017-01-24 23:07
Thanks @plttlqh, I'm not entirely sure what the issue is. How urgently do you need this looked at?

**Comment by plttlqh** [comment] 2017-02-06 07:41
thank @shakeelmohamed, It's not urgent for my team at all. I'm researching for my team, we can wait. :). I can see how convenient of using Splunk :)

**Comment by tdhellmann** [comment] 2018-06-01 17:55
We don't really have the information necessary to debug this - I'm going to close the issue out, but feel free to come back with additional detail if you are still experiencing this issue.

**Closed by tdhellmann** 2018-06-01 17:55 UTC
